/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'

const LoginLazyRouteImport = createFileRoute('/login')()
const AuthIndexLazyRouteImport = createFileRoute('/_auth/')()
const AuthTeachLazyRouteImport = createFileRoute('/_auth/teach')()
const AuthReviewLazyRouteImport = createFileRoute('/_auth/review')()
const AuthKnowledgeLazyRouteImport = createFileRoute('/_auth/knowledge')()
const AuthIngestLazyRouteImport = createFileRoute('/_auth/ingest')()
const AuthChatLazyRouteImport = createFileRoute('/_auth/chat')()
const AuthAnalyzeLazyRouteImport = createFileRoute('/_auth/analyze')()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexLazyRoute = AuthIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/index.lazy').then((d) => d.Route))
const AuthTeachLazyRoute = AuthTeachLazyRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/teach.lazy').then((d) => d.Route))
const AuthReviewLazyRoute = AuthReviewLazyRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/review.lazy').then((d) => d.Route))
const AuthKnowledgeLazyRoute = AuthKnowledgeLazyRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/knowledge.lazy').then((d) => d.Route),
)
const AuthIngestLazyRoute = AuthIngestLazyRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/ingest.lazy').then((d) => d.Route))
const AuthChatLazyRoute = AuthChatLazyRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/chat.lazy').then((d) => d.Route))
const AuthAnalyzeLazyRoute = AuthAnalyzeLazyRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/analyze.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/analyze': typeof AuthAnalyzeLazyRoute
  '/chat': typeof AuthChatLazyRoute
  '/ingest': typeof AuthIngestLazyRoute
  '/knowledge': typeof AuthKnowledgeLazyRoute
  '/review': typeof AuthReviewLazyRoute
  '/teach': typeof AuthTeachLazyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginLazyRoute
  '/analyze': typeof AuthAnalyzeLazyRoute
  '/chat': typeof AuthChatLazyRoute
  '/ingest': typeof AuthIngestLazyRoute
  '/knowledge': typeof AuthKnowledgeLazyRoute
  '/review': typeof AuthReviewLazyRoute
  '/teach': typeof AuthTeachLazyRoute
  '/': typeof AuthIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/_auth/analyze': typeof AuthAnalyzeLazyRoute
  '/_auth/chat': typeof AuthChatLazyRoute
  '/_auth/ingest': typeof AuthIngestLazyRoute
  '/_auth/knowledge': typeof AuthKnowledgeLazyRoute
  '/_auth/review': typeof AuthReviewLazyRoute
  '/_auth/teach': typeof AuthTeachLazyRoute
  '/_auth/': typeof AuthIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analyze'
    | '/chat'
    | '/ingest'
    | '/knowledge'
    | '/review'
    | '/teach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analyze'
    | '/chat'
    | '/ingest'
    | '/knowledge'
    | '/review'
    | '/teach'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/analyze'
    | '/_auth/chat'
    | '/_auth/ingest'
    | '/_auth/knowledge'
    | '/_auth/review'
    | '/_auth/teach'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/teach': {
      id: '/_auth/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof AuthTeachLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/review': {
      id: '/_auth/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthReviewLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/knowledge': {
      id: '/_auth/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthKnowledgeLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ingest': {
      id: '/_auth/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof AuthIngestLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/analyze': {
      id: '/_auth/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthAnalyzeLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAnalyzeLazyRoute: typeof AuthAnalyzeLazyRoute
  AuthChatLazyRoute: typeof AuthChatLazyRoute
  AuthIngestLazyRoute: typeof AuthIngestLazyRoute
  AuthKnowledgeLazyRoute: typeof AuthKnowledgeLazyRoute
  AuthReviewLazyRoute: typeof AuthReviewLazyRoute
  AuthTeachLazyRoute: typeof AuthTeachLazyRoute
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAnalyzeLazyRoute: AuthAnalyzeLazyRoute,
  AuthChatLazyRoute: AuthChatLazyRoute,
  AuthIngestLazyRoute: AuthIngestLazyRoute,
  AuthKnowledgeLazyRoute: AuthKnowledgeLazyRoute,
  AuthReviewLazyRoute: AuthReviewLazyRoute,
  AuthTeachLazyRoute: AuthTeachLazyRoute,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
